name: Deploy to GitHub Pages

# 每次程式碼Push到master，執行workflow
on:
  push:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
    # 使用ubuntu
    runs-on: ubuntu-latest
    env:
      PAGES_BASE_PATH: /${{ github.event.repository.name }}/
    steps:
    # 使用checkout actions
    - uses: actions/checkout@v2
    
    # 安裝.NET Core SDK 3.1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x   
    
    # 執行單元測試專案
    - name: Run Unit Test 
      run: dotnet test --no-build
      
    # 發佈程式到Release資料夾
    - name: Publish .NET Core Project
      run: dotnet publish Blog/Blog.csproj -c Release -o Prerender/output --nologo
      
    # Use NodeJS react-snap utitility to prerender static website
    - name: prerender Blazor client
      working-directory: Prerender
      run: npx react-snap

    # GitHub Pages 專案頁面會部署在 /<repo-name>/，需要調整 base href
    - name: Update base href for GitHub Pages
      working-directory: Prerender/output/wwwroot
      run: |
        find . -name "*.html" | while read htmlFile; do
            sed -i "s#<base href=\"/\" />#<base href=\"${PAGES_BASE_PATH}\" />#g" "$htmlFile"
        done
    
    # Delete script in all html files to include subfolder
    - name: Delete script
      working-directory: Prerender/output/wwwroot
      run: |
        find . -name "*.html" | while read htmlFile; do
            sed -i 's/<script>var Module; window.__wasmmodulecallback__(); delete window.__wasmmodulecallback__;<\/script>//g' "$htmlFile"
            sed -i 's#<script src="_framework/dotnet.6.0.14.iiw8sbvu70.js" defer="" integrity="sha256-54cJ6JdGhGbKaLWxHfRYzYbuyRq2wlK/ZDzfSXD3FEs=" crossorigin="anonymous"></script>##g' "$htmlFile"
        done
    
    # 複製index.html內容到404.html
    - name: copy index.html to 404.html
      run: cp Prerender/output/wwwroot/index.html Prerender/output/wwwroot/404.html

    # 加入一個.nojekyll檔案
    - name: Add .nojekyll file
      run: touch Prerender/output/wwwroot/.nojekyll
    
    # 將release/wwwroot的程式碼，push到gh-pages分支
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        GITHUB_TOKEN: ${{ secrets.BLOGTOKEN }}
        BRANCH: gh-pages
        FOLDER: Prerender/output/wwwroot
